FROM apache/spark:3.4.1-scala2.12-java11-python3-r-ubuntu

COPY guava-32.1.1-jre.jar /opt/spark/jars/guava-14.0.1.jar
COPY protobuf-java-3.23.4.jar /opt/spark/jars/protobuf-java-2.5.0.jar
COPY failureaccess-1.0.1.jar /opt/spark/jars/failureaccess-1.0.1.jar