{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmission",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 27645,
          "sha512": "3f22963f8fb7cf0936912ad6de3033b3480d87dad89160f17cb6769f1f35a4aa24d0e5c115386bc71484e62484dd82e1d0c25bca972d416ced96c8c9b1d276fe",
          "sha256": "a13a2850c34d9213707fb2ea4db9be29ea4b427f40d9d9e8a40a5d8da7d17add",
          "sha1": "65e6c6ee458ba7d896bd6b2dad40cf8f872c626c",
          "md5": "190eb37df9d00e44a12674ee2338846b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 27645,
          "sha512": "3f22963f8fb7cf0936912ad6de3033b3480d87dad89160f17cb6769f1f35a4aa24d0e5c115386bc71484e62484dd82e1d0c25bca972d416ced96c8c9b1d276fe",
          "sha256": "a13a2850c34d9213707fb2ea4db9be29ea4b427f40d9d9e8a40a5d8da7d17add",
          "sha1": "65e6c6ee458ba7d896bd6b2dad40cf8f872c626c",
          "md5": "190eb37df9d00e44a12674ee2338846b"
        }
      ]
    }
  ]
}
