{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmission",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 28561,
          "sha512": "57262feb9a90fff67a8754d9d7c1cad8d08b404ebbc19c9b29e82568e65e54f9f2c49b9dc4473820ec8ba00fe27a0aaafbc546f4e9c03512e078907cc1947f61",
          "sha256": "d2780c6efa75daf7209efd959e721e7c23acd671dcdfe53b89f3237116941f3e",
          "sha1": "1c8d00ebcc8ca230aec84493f270c4edc07dc31e",
          "md5": "de31b6fd8f66e6737ecae5eb2984d576"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive-thriftserver_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 28561,
          "sha512": "57262feb9a90fff67a8754d9d7c1cad8d08b404ebbc19c9b29e82568e65e54f9f2c49b9dc4473820ec8ba00fe27a0aaafbc546f4e9c03512e078907cc1947f61",
          "sha256": "d2780c6efa75daf7209efd959e721e7c23acd671dcdfe53b89f3237116941f3e",
          "sha1": "1c8d00ebcc8ca230aec84493f270c4edc07dc31e",
          "md5": "de31b6fd8f66e6737ecae5eb2984d576"
        }
      ]
    }
  ]
}
