{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmission",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 27751,
          "sha512": "2f516388796b2673f49441ffa016d2932aac2039613e45666a1be7106816445f3862744af14984be3e3b0e1eed0dc7a938187ca2036b7db0251e77cc7a749dd5",
          "sha256": "972b31294285127b708db75c3a3c84fbe0bad17e791ba26ff68c5b7fea02c4bc",
          "sha1": "1c2709cea596d5222d1c694f57ec032fcab28270",
          "md5": "2d8799a8816dc6d5f972a14db027f427"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmission-1.0.0.jar",
          "url": "codesubmission-1.0.0.jar",
          "size": 27751,
          "sha512": "2f516388796b2673f49441ffa016d2932aac2039613e45666a1be7106816445f3862744af14984be3e3b0e1eed0dc7a938187ca2036b7db0251e77cc7a749dd5",
          "sha256": "972b31294285127b708db75c3a3c84fbe0bad17e791ba26ff68c5b7fea02c4bc",
          "sha1": "1c2709cea596d5222d1c694f57ec032fcab28270",
          "md5": "2d8799a8816dc6d5f972a14db027f427"
        }
      ]
    }
  ]
}
