{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 19850,
          "sha512": "7ab06989cc96a8d6f5f98c51521a8f521873eb4fdc80aef65a87de237c149b937927df966b01be9143c415add0ab55cfc3ed9e82c98ce685b407d9505033887c",
          "sha256": "05b9d71311096e6cc6730e2e03d073d20c10c8e3768597f2d7ac05383dab8123",
          "sha1": "def423709e1004724ee55552c6bfdaaddfc63b07",
          "md5": "b5ae1333649921f0acc2d8aff0aee6d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect-client-jvm_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 19850,
          "sha512": "7ab06989cc96a8d6f5f98c51521a8f521873eb4fdc80aef65a87de237c149b937927df966b01be9143c415add0ab55cfc3ed9e82c98ce685b407d9505033887c",
          "sha256": "05b9d71311096e6cc6730e2e03d073d20c10c8e3768597f2d7ac05383dab8123",
          "sha1": "def423709e1004724ee55552c6bfdaaddfc63b07",
          "md5": "b5ae1333649921f0acc2d8aff0aee6d4"
        }
      ]
    }
  ]
}
