{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 19850,
          "sha512": "70b42a3d18e37b74a11c74d7a6520f436a6930eb01673cc97cdd444e5a448f8521c2e7503193663d93312fde7d98b2fbc38e0e737ed6db20bfbab87abb35e65d",
          "sha256": "d9684ea3d7350772b7956355379025612d425273b8452aaac4d01bbed7feadd3",
          "sha1": "afb647052ddf13d145afe82eb968bba78fabd14c",
          "md5": "1e39b601e01f4f339cc2ee1276d8a494"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect-client-jvm_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 19850,
          "sha512": "70b42a3d18e37b74a11c74d7a6520f436a6930eb01673cc97cdd444e5a448f8521c2e7503193663d93312fde7d98b2fbc38e0e737ed6db20bfbab87abb35e65d",
          "sha256": "d9684ea3d7350772b7956355379025612d425273b8452aaac4d01bbed7feadd3",
          "sha1": "afb647052ddf13d145afe82eb968bba78fabd14c",
          "md5": "1e39b601e01f4f339cc2ee1276d8a494"
        }
      ]
    }
  ]
}
