{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 19858,
          "sha512": "106f35bcb3aa53b592123ae1fd3c47679e8331fb458ffeaa8c841e5f7b559ef8418d499df0c40ad10933053852a9c1f73307b7b473258d30de418b3c2f8b3c32",
          "sha256": "70b86f0aa443b79f6863f237f16623e67d8b5a85b2b13dfb0de3c81603f22e7d",
          "sha1": "007203937810588646cc50ed036226dc3f8fe364",
          "md5": "d77b658785ee63700fb6fcdc2d5b7381"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect-client-jvm_2.12",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmit-1.0.0.jar",
          "url": "codesubmit-1.0.0.jar",
          "size": 19858,
          "sha512": "106f35bcb3aa53b592123ae1fd3c47679e8331fb458ffeaa8c841e5f7b559ef8418d499df0c40ad10933053852a9c1f73307b7b473258d30de418b3c2f8b3c32",
          "sha256": "70b86f0aa443b79f6863f237f16623e67d8b5a85b2b13dfb0de3c81603f22e7d",
          "sha1": "007203937810588646cc50ed036226dc3f8fe364",
          "md5": "d77b658785ee63700fb6fcdc2d5b7381"
        }
      ]
    }
  ]
}
