{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmission-client",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmission-client-1.0.0.jar",
          "url": "codesubmission-client-1.0.0.jar",
          "size": 10146,
          "sha512": "7decd6fc48a692ae09fb68434a5a867e20fb7602f017420f19730134fc3b48ef7dc95e289fc6a5ccdb34ec7dd2aa02a9929a6d2e5a39699f089deab8b217d9f7",
          "sha256": "6e20b8a7a65ccfa3102c39d47801aa19f5dde18186f0f8d024f4d9f250bc2217",
          "sha1": "dbdcf1915311e1e6f1bbadaf4154d8b5f54f70fe",
          "md5": "78474c64bce883a1b38f05f33320a87a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.hive",
          "module": "hive-jdbc",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "flight-sql-jdbc-core",
          "version": {
            "requires": "12.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmission-client-1.0.0.jar",
          "url": "codesubmission-client-1.0.0.jar",
          "size": 10146,
          "sha512": "7decd6fc48a692ae09fb68434a5a867e20fb7602f017420f19730134fc3b48ef7dc95e289fc6a5ccdb34ec7dd2aa02a9929a6d2e5a39699f089deab8b217d9f7",
          "sha256": "6e20b8a7a65ccfa3102c39d47801aa19f5dde18186f0f8d024f4d9f250bc2217",
          "sha1": "dbdcf1915311e1e6f1bbadaf4154d8b5f54f70fe",
          "md5": "78474c64bce883a1b38f05f33320a87a"
        }
      ]
    }
  ]
}
