{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmission-client",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmission-client-1.0.0.jar",
          "url": "codesubmission-client-1.0.0.jar",
          "size": 10146,
          "sha512": "da3095c28a8de4e9d26ef7e6c3a54bbdd8aa1ad5abae456edae899891b7e2b1e9aa120ebcd2191e0521bcea2f7a2e0c1e2bd5974eac0a3f865b4ef984201ebfc",
          "sha256": "3a4fc0dfb3fe9f9df37116f83112a3c9dff884fdb37057e2303945c4549addc1",
          "sha1": "cd1fb350b67b645ab646e505aaa598523bfec706",
          "md5": "90f0ae72b604929d560937d6dc3b0f6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.hive",
          "module": "hive-jdbc",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "flight-sql-jdbc-core",
          "version": {
            "requires": "12.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmission-client-1.0.0.jar",
          "url": "codesubmission-client-1.0.0.jar",
          "size": 10146,
          "sha512": "da3095c28a8de4e9d26ef7e6c3a54bbdd8aa1ad5abae456edae899891b7e2b1e9aa120ebcd2191e0521bcea2f7a2e0c1e2bd5974eac0a3f865b4ef984201ebfc",
          "sha256": "3a4fc0dfb3fe9f9df37116f83112a3c9dff884fdb37057e2303945c4549addc1",
          "sha1": "cd1fb350b67b645ab646e505aaa598523bfec706",
          "md5": "90f0ae72b604929d560937d6dc3b0f6b"
        }
      ]
    }
  ]
}
