{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmission-client",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmission-client-1.0.0.jar",
          "url": "codesubmission-client-1.0.0.jar",
          "size": 10092,
          "sha512": "c151b2af751c7d02bf6f9b30a79d1c28885f6941bebcfff236de03af96f72291f2dc32dcc4e87b31891e656348f050a7d58bdb36daba24e8960dd568319751bc",
          "sha256": "b05835d45b4065ecc6a6d7911af43979deb8c9a701341a19d6adec180ee03583",
          "sha1": "a38d43e25d92cbeaca3e51ab88e601f8c1f37de4",
          "md5": "9908ba7df28f67d0e22f4c9c4859fe5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmission-client-1.0.0.jar",
          "url": "codesubmission-client-1.0.0.jar",
          "size": 10092,
          "sha512": "c151b2af751c7d02bf6f9b30a79d1c28885f6941bebcfff236de03af96f72291f2dc32dcc4e87b31891e656348f050a7d58bdb36daba24e8960dd568319751bc",
          "sha256": "b05835d45b4065ecc6a6d7911af43979deb8c9a701341a19d6adec180ee03583",
          "sha1": "a38d43e25d92cbeaca3e51ab88e601f8c1f37de4",
          "md5": "9908ba7df28f67d0e22f4c9c4859fe5f"
        }
      ]
    }
  ]
}
