{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmission-server",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmission-server-1.0.0.jar",
          "url": "codesubmission-server-1.0.0.jar",
          "size": 67429,
          "sha512": "b9fc98495e0d582d961027883fc7774418f298eb6f185be338ca523e2049695c8a89293d46436c5df45a771e728baed90de0e0722d32edc61c756e4a5355698e",
          "sha256": "23344643b01608ca2eea715cbdcbdb00c58a87129fa11f00cbbeb84070e0e8df",
          "sha1": "b9ad009794c4633d186e5d3128cd3e35e9e3c074",
          "md5": "cf9e48256567229e1791f47067bfa7f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-repl_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive-thriftserver_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "flight-sql",
          "version": {
            "requires": "12.0.1"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "flight-sql-jdbc-core",
          "version": {
            "requires": "12.0.1"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "flight-core",
          "version": {
            "requires": "12.0.1"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "arrow-flight",
          "version": {
            "requires": "12.0.1"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "arrow-jdbc",
          "version": {
            "requires": "12.0.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.23.0"
          }
        },
        {
          "group": "io.kubernetes",
          "module": "client-java",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-client",
          "version": {
            "requires": "6.7.2"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.6.0.202305301015-r"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.1-jre"
          }
        },
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmission-server-1.0.0.jar",
          "url": "codesubmission-server-1.0.0.jar",
          "size": 67429,
          "sha512": "b9fc98495e0d582d961027883fc7774418f298eb6f185be338ca523e2049695c8a89293d46436c5df45a771e728baed90de0e0722d32edc61c756e4a5355698e",
          "sha256": "23344643b01608ca2eea715cbdcbdb00c58a87129fa11f00cbbeb84070e0e8df",
          "sha1": "b9ad009794c4633d186e5d3128cd3e35e9e3c074",
          "md5": "cf9e48256567229e1791f47067bfa7f4"
        }
      ]
    }
  ]
}
