{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "codesubmission-server",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codesubmission-server-1.0.0.jar",
          "url": "codesubmission-server-1.0.0.jar",
          "size": 67577,
          "sha512": "1159bcfd274e50f5bbd76034e68ca40e8c7e075d409c67fbb5d722607fad8d10e39eb44ec3d7100370eba6b8ef485764842604d0f11f34959471f34d7f970ba9",
          "sha256": "6995ec8e4a4aa2141ae3c29f78d0625f1c6c055540ef01da2270778948a6df24",
          "sha1": "023d238a85f47ee83b9720b1d818e7f806923047",
          "md5": "b8eee831c36bef4189d62f4a901db586"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-repl_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive-thriftserver_2.12",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "flight-sql",
          "version": {
            "requires": "12.0.1"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "flight-sql-jdbc-core",
          "version": {
            "requires": "12.0.1"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "flight-core",
          "version": {
            "requires": "12.0.1"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "arrow-flight",
          "version": {
            "requires": "12.0.1"
          }
        },
        {
          "group": "org.apache.arrow",
          "module": "arrow-jdbc",
          "version": {
            "requires": "12.0.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.23.0"
          }
        },
        {
          "group": "io.kubernetes",
          "module": "client-java",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-client",
          "version": {
            "requires": "6.7.2"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.6.0.202305301015-r"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.1-jre"
          }
        },
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "codesubmission-server-1.0.0.jar",
          "url": "codesubmission-server-1.0.0.jar",
          "size": 67577,
          "sha512": "1159bcfd274e50f5bbd76034e68ca40e8c7e075d409c67fbb5d722607fad8d10e39eb44ec3d7100370eba6b8ef485764842604d0f11f34959471f34d7f970ba9",
          "sha256": "6995ec8e4a4aa2141ae3c29f78d0625f1c6c055540ef01da2270778948a6df24",
          "sha1": "023d238a85f47ee83b9720b1d818e7f806923047",
          "md5": "b8eee831c36bef4189d62f4a901db586"
        }
      ]
    }
  ]
}
